---
development:
  cloud_name: bisonshare
  api_key: '265537665961479'
  api_secret: wZBiVoQeojDkEYYsd-JxXVj_73Q
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: bisonshare
  api_key: '265537665961479'
  api_secret: wZBiVoQeojDkEYYsd-JxXVj_73Q
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: bisonshare
  api_key: '265537665961479'
  api_secret: wZBiVoQeojDkEYYsd-JxXVj_73Q
  enhance_image_tag: true
  static_image_support: false
